/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Subjects */
        get: operations["list_subjects_subjects_get"];
        put?: never;
        /** Create Subject */
        post: operations["create_subject_subjects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects/{subject_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Subject */
        get: operations["get_subject_subjects__subject_id__get"];
        put?: never;
        post?: never;
        /** Delete Subject */
        delete: operations["delete_subject_subjects__subject_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects/{subject_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_subjects__subject_id__documents_get"];
        put?: never;
        /** Create Document */
        post: operations["create_document_subjects__subject_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects/{subject_id}/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_subjects__subject_id__documents__document_id__get"];
        put?: never;
        post?: never;
        /** Delete Document */
        delete: operations["delete_document_subjects__subject_id__documents__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects/{subject_id}/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask Question */
        post: operations["ask_question_subjects__subject_id__ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects/{subject_id}/ask/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask Question Stream */
        post: operations["ask_question_stream_subjects__subject_id__ask_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Conversations */
        get: operations["list_conversations_conversations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Conversation */
        get: operations["get_conversation_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        /** Delete Conversation */
        delete: operations["delete_conversation_conversations__conversation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects/{subject_id}/quizzes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Quizzes */
        get: operations["list_quizzes_subjects__subject_id__quizzes_get"];
        put?: never;
        /** Generate Quiz */
        post: operations["generate_quiz_subjects__subject_id__quizzes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects/{subject_id}/quizzes/{quiz_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Quiz */
        get: operations["get_quiz_subjects__subject_id__quizzes__quiz_id__get"];
        put?: never;
        post?: never;
        /** Delete Quiz */
        delete: operations["delete_quiz_subjects__subject_id__quizzes__quiz_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects/{subject_id}/flashcards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Flashcards */
        get: operations["list_flashcards_subjects__subject_id__flashcards_get"];
        put?: never;
        /** Generate Flashcards */
        post: operations["generate_flashcards_subjects__subject_id__flashcards_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects/{subject_id}/flashcards/due": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Due Flashcards */
        get: operations["list_due_flashcards_subjects__subject_id__flashcards_due_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/flashcards/{flashcard_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Flashcard */
        post: operations["review_flashcard_flashcards__flashcard_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/flashcards/{flashcard_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Flashcard */
        delete: operations["delete_flashcard_flashcards__flashcard_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects/{subject_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Subject Progress */
        get: operations["get_subject_progress_subjects__subject_id__progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Overall Progress */
        get: operations["get_overall_progress_progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Plan */
        get: operations["get_plan_billing_plan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Checkout
         * @description Start a Polar checkout for a paid plan. Authenticated: `owner_id` comes from the
         *     caller's verified Clerk token and is what gets linked to the Polar customer, so a
         *     caller can only ever buy a plan for themselves.
         */
        post: operations["create_checkout_billing_checkout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Polar Webhook
         * @description Polar -> us. **Public endpoint, no Clerk auth** (Polar has no user token to send),
         *     so the signature IS the authentication.
         *
         *     Order matters and is load-bearing:
         *       1. read the **raw** body — the signature covers those exact bytes, so parsing to
         *          JSON and re-serializing would change them and break verification;
         *       2. verify the signature;
         *       3. only then touch the payload or the DB.
         *     An unverified webhook would let anyone POST themselves onto Business for free, which
         *     is why there is no path to step 3 that skips step 2 — including when no secret is
         *     configured, which raises rather than defaulting to "accept".
         *
         *     `async def` on purpose: `await request.body()` needs it, and it's the only way to get
         *     the raw bytes.
         */
        post: operations["polar_webhook_billing_webhook_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/referral": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Referral */
        get: operations["get_referral_referral_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/referral/redeem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Redeem Referral */
        post: operations["redeem_referral_referral_redeem_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Assignments */
        get: operations["list_assignments_assignments_get"];
        put?: never;
        /** Create Assignment */
        post: operations["create_assignment_assignments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assignments/{assignment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Assignment */
        get: operations["get_assignment_assignments__assignment_id__get"];
        put?: never;
        post?: never;
        /** Delete Assignment */
        delete: operations["delete_assignment_assignments__assignment_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assignments/{assignment_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Assignment */
        post: operations["submit_assignment_assignments__assignment_id__submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assignments/{assignment_id}/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Submissions */
        get: operations["list_submissions_assignments__assignment_id__submissions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assignments/{assignment_id}/my-submission": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Submission */
        get: operations["get_my_submission_assignments__assignment_id__my_submission_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inngest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Api Inngest */
        get: operations["get_api_inngest_api_inngest_get"];
        /** Put Inngest Api */
        put: operations["put_inngest_api_api_inngest_put"];
        /** Post Inngest Api */
        post: operations["post_inngest_api_api_inngest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness check — confirms the API process is up.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/org": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Whoami Org
         * @description The caller's active-organization context as the backend actually sees it, read
         *     from the verified Clerk session JWT (`get_org_context`).
         *
         *     Permanent, authenticated debug/verification endpoint (Phase 5 increment 2, Step 0):
         *     org-scoped content sharing is built entirely on `org_id`/`org_role` arriving in the
         *     real token. Increment 1 only exercised `get_org_context` in unit tests, never
         *     against a live token — this endpoint lets the org sharing model be confirmed
         *     end-to-end: signed in with an active org, `org_id`/`org_role` must be non-null here.
         *     If they are null in a real session that HAS an active org, Clerk's session-token JWT
         *     template is missing the org claims and must be configured (backend code is correct;
         *     do NOT touch `.env`/Clerk config from here). Returns only the caller's own ids —
         *     never anyone else's — so it's safe to keep enabled.
         */
        get: operations["whoami_org_org_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AskRequest */
        AskRequest: {
            /** Question */
            question: string;
            /** Conversation Id */
            conversation_id?: string | null;
        };
        /** AskResponse */
        AskResponse: {
            /** Answer */
            answer: string;
            /** Sources */
            sources: components["schemas"]["SourceChunk"][];
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
        };
        /** AssignmentCreate */
        AssignmentCreate: {
            /** Title */
            title: string;
            /**
             * Subject Id
             * Format: uuid
             */
            subject_id: string;
            /** Description */
            description?: string | null;
            /** Quiz Id */
            quiz_id?: string | null;
            /** Due At */
            due_at?: string | null;
        };
        /** AssignmentRead */
        AssignmentRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Org Id */
            org_id: string;
            /** Owner Id */
            owner_id: string;
            /**
             * Subject Id
             * Format: uuid
             */
            subject_id: string;
            /** Quiz Id */
            quiz_id?: string | null;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Due At */
            due_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * AssignmentSubmissionCreate
         * @description A student's self-reported completion payload. Both fields optional — the mere act
         *     of submitting records completion; `score`/`note` are extras the student may attach.
         *     Bounded (score 0–100, note length) so a client can't push nonsense values.
         */
        AssignmentSubmissionCreate: {
            /** Score */
            score?: number | null;
            /** Note */
            note?: string | null;
        };
        /** AssignmentSubmissionRead */
        AssignmentSubmissionRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Assignment Id
             * Format: uuid
             */
            assignment_id: string;
            /** Owner Id */
            owner_id: string;
            /**
             * Completed At
             * Format: date-time
             */
            completed_at: string;
            /** Score */
            score?: number | null;
            /** Note */
            note?: string | null;
        };
        /** Body_create_document_subjects__subject_id__documents_post */
        Body_create_document_subjects__subject_id__documents_post: {
            /** File */
            file: string;
            /**
             * Language
             * @default en
             */
            language: string;
        };
        /**
         * CheckoutCreateRequest
         * @description Which plan to buy. The caller names a *plan*, never a Polar product id — product
         *     ids are server-side config (see config.polar_product_id_*), so a client can't point a
         *     checkout at an arbitrary product. There is no `owner_id` here either: it comes from
         *     the caller's verified token, so nobody can check out on someone else's behalf.
         */
        CheckoutCreateRequest: {
            plan: components["schemas"]["Plan"];
            /** Success Url */
            success_url?: string | null;
        };
        /** CheckoutCreateResponse */
        CheckoutCreateResponse: {
            /** Checkout Url */
            checkout_url: string;
        };
        /** ConversationRead */
        ConversationRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Subject Id
             * Format: uuid
             */
            subject_id: string;
            /** Title */
            title: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ConversationTurnRead */
        ConversationTurnRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Question */
            question: string;
            /** Answer */
            answer: string;
            /** Sources */
            sources: components["schemas"]["SourceChunk"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ConversationWithTurns */
        ConversationWithTurns: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Subject Id
             * Format: uuid
             */
            subject_id: string;
            /** Title */
            title: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Turns */
            turns: components["schemas"]["ConversationTurnRead"][];
        };
        /** DocumentRead */
        DocumentRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Subject Id
             * Format: uuid
             */
            subject_id: string;
            /** Filename */
            filename: string;
            /** Content Type */
            content_type: string;
            status: components["schemas"]["DocumentStatus"];
            /** Summary */
            summary: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * DocumentStatus
         * @enum {string}
         */
        DocumentStatus: "pending" | "ready" | "failed";
        /** DocumentStatusCounts */
        DocumentStatusCounts: {
            /** Total */
            total: number;
            /** Ready */
            ready: number;
            /** Pending */
            pending: number;
            /** Failed */
            failed: number;
        };
        /** FlashcardGenerateRequest */
        FlashcardGenerateRequest: {
            /**
             * Num Cards
             * @default 10
             */
            num_cards: number;
            /**
             * Language
             * @default en
             */
            language: string;
        };
        /** FlashcardProgress */
        FlashcardProgress: {
            /** Total */
            total: number;
            /** Due */
            due: number;
            /** New */
            new: number;
            /** Learning */
            learning: number;
            /** Mature */
            mature: number;
        };
        /** FlashcardRead */
        FlashcardRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Subject Id
             * Format: uuid
             */
            subject_id: string;
            /** Front */
            front: string;
            /** Back */
            back: string;
            /** Repetitions */
            repetitions: number;
            /** Ease Factor */
            ease_factor: number;
            /** Interval Days */
            interval_days: number;
            /**
             * Due At
             * Format: date-time
             */
            due_at: string;
            /** Last Reviewed At */
            last_reviewed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** OverallProgress */
        OverallProgress: {
            /** Subject Count */
            subject_count: number;
            documents: components["schemas"]["DocumentStatusCounts"];
            flashcards: components["schemas"]["FlashcardProgress"];
            /** Quiz Count */
            quiz_count: number;
        };
        /**
         * Plan
         * @enum {string}
         */
        Plan: "free" | "pro" | "business";
        /**
         * PlanLimitsRead
         * @description `null` means unlimited for that dimension (Business).
         */
        PlanLimitsRead: {
            /** Max Subjects */
            max_subjects: number | null;
            /** Max Documents Per Subject */
            max_documents_per_subject: number | null;
            /** Max Generations Per Day */
            max_generations_per_day: number | null;
        };
        /** PlanRead */
        PlanRead: {
            plan: components["schemas"]["Plan"];
            limits: components["schemas"]["PlanLimitsRead"];
            usage: components["schemas"]["PlanUsageRead"];
        };
        /**
         * PlanUsageRead
         * @description Current usage against the caps that are countable account-wide.
         *
         *     `max_documents_per_subject` has no entry here on purpose — it's a *per-subject*
         *     cap, so there's no single account-wide number for it. The frontend gets the cap in
         *     `limits` (to state the rule) and the per-subject count from the existing
         *     `GET /subjects/{id}/progress` documents total.
         */
        PlanUsageRead: {
            /** Subjects */
            subjects: number;
            /** Generations Today */
            generations_today: number;
        };
        /** QuizGenerateRequest */
        QuizGenerateRequest: {
            /**
             * Num Questions
             * @default 5
             */
            num_questions: number;
            /** Title */
            title?: string | null;
            /**
             * Language
             * @default en
             */
            language: string;
        };
        /** QuizQuestionRead */
        QuizQuestionRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Question */
            question: string;
            /** Options */
            options: string[];
            /** Correct Index */
            correct_index: number;
            /** Explanation */
            explanation: string | null;
            /** Order */
            order: number;
        };
        /**
         * QuizRead
         * @description List/summary shape — no questions (the list endpoint doesn't load them).
         */
        QuizRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Subject Id
             * Format: uuid
             */
            subject_id: string;
            /** Title */
            title: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** QuizWithQuestions */
        QuizWithQuestions: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Subject Id
             * Format: uuid
             */
            subject_id: string;
            /** Title */
            title: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Questions */
            questions: components["schemas"]["QuizQuestionRead"][];
        };
        /**
         * ReferralRead
         * @description The caller's own referral code plus how many people they've referred.
         */
        ReferralRead: {
            /** Code */
            code: string;
            /** Referred Count */
            referred_count: number;
        };
        /** ReferralRedeemRequest */
        ReferralRedeemRequest: {
            /** Code */
            code: string;
        };
        /** ReviewRequest */
        ReviewRequest: {
            /** Grade */
            grade: number;
        };
        /** SourceChunk */
        SourceChunk: {
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Filename */
            filename: string;
            /** Chunk Index */
            chunk_index: number;
            /** Text */
            text: string;
            /** Similarity Score */
            similarity_score: number;
        };
        /** SubjectCreate */
        SubjectCreate: {
            /** Name */
            name: string;
        };
        /** SubjectProgress */
        SubjectProgress: {
            /**
             * Subject Id
             * Format: uuid
             */
            subject_id: string;
            documents: components["schemas"]["DocumentStatusCounts"];
            flashcards: components["schemas"]["FlashcardProgress"];
            /** Quiz Count */
            quiz_count: number;
        };
        /** SubjectRead */
        SubjectRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Org Id */
            org_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WebhookResponse
         * @description What the webhook reports back to Polar. `status` is one of `applied`,
         *     `ignored`, or `ignored_stale` — an accepted-but-not-actioned event is a 200 with an
         *     explicit outcome, not a silent success (rule 3).
         */
        WebhookResponse: {
            /** Status */
            status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_subjects_subjects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectRead"][];
                };
            };
        };
    };
    create_subject_subjects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_subject_subjects__subject_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_subject_subjects__subject_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_subjects__subject_id__documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_document_subjects__subject_id__documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_document_subjects__subject_id__documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_subjects__subject_id__documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: string;
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_subjects__subject_id__documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: string;
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_question_subjects__subject_id__ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_question_stream_subjects__subject_id__ask_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversations_conversations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationRead"][];
                };
            };
        };
    };
    get_conversation_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationWithTurns"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_conversation_conversations__conversation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_quizzes_subjects__subject_id__quizzes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_quiz_subjects__subject_id__quizzes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuizGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizWithQuestions"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quiz_subjects__subject_id__quizzes__quiz_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: string;
                quiz_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizWithQuestions"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_quiz_subjects__subject_id__quizzes__quiz_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: string;
                quiz_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_flashcards_subjects__subject_id__flashcards_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlashcardRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_flashcards_subjects__subject_id__flashcards_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlashcardGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlashcardRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_due_flashcards_subjects__subject_id__flashcards_due_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlashcardRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_flashcard_flashcards__flashcard_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                flashcard_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlashcardRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_flashcard_flashcards__flashcard_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                flashcard_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_subject_progress_subjects__subject_id__progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectProgress"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_overall_progress_progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverallProgress"];
                };
            };
        };
    };
    get_plan_billing_plan_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanRead"];
                };
            };
        };
    };
    create_checkout_billing_checkout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    polar_webhook_billing_webhook_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookResponse"];
                };
            };
        };
    };
    get_referral_referral_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferralRead"];
                };
            };
        };
    };
    redeem_referral_referral_redeem_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReferralRedeemRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_assignments_assignments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentRead"][];
                };
            };
        };
    };
    create_assignment_assignments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignmentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_assignment_assignments__assignment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_assignment_assignments__assignment_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_assignment_assignments__assignment_id__submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignmentSubmissionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentSubmissionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_submissions_assignments__assignment_id__submissions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentSubmissionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_submission_assignments__assignment_id__my_submission_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentSubmissionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_api_inngest_api_inngest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    put_inngest_api_api_inngest_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    post_inngest_api_api_inngest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    whoami_org_org_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string | null;
                    };
                };
            };
        };
    };
}
