"""add telegram_links and telegram_link_codes tables (Phase 7)

Revision ID: 06650625fb97
Revises: 6c9f0c767feb
Create Date: 2026-07-20 13:39:24.687564

"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401 — used when autogenerate emits pgvector column types
import sqlalchemy as sa
import sqlmodel  # noqa: F401 — used when autogenerate emits SQLModel column types

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "06650625fb97"
down_revision: str | Sequence[str] | None = "6c9f0c767feb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "telegram_link_codes",
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("owner_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("used", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_index(
        op.f("ix_telegram_link_codes_owner_id"),
        "telegram_link_codes",
        ["owner_id"],
        unique=False,
    )
    op.create_table(
        "telegram_links",
        sa.Column("telegram_chat_id", sa.BigInteger(), nullable=False),
        sa.Column("owner_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("telegram_chat_id"),
    )
    op.create_index(
        op.f("ix_telegram_links_owner_id"), "telegram_links", ["owner_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_telegram_links_owner_id"), table_name="telegram_links")
    op.drop_table("telegram_links")
    op.drop_index(op.f("ix_telegram_link_codes_owner_id"), table_name="telegram_link_codes")
    op.drop_table("telegram_link_codes")
    # ### end Alembic commands ###
