"""add org_id to subjects

Revision ID: 3441b9fb9f25
Revises: e30f18904b8f
Create Date: 2026-07-19 16:48:34.832300

"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401 — used when autogenerate emits pgvector column types
import sqlalchemy as sa
import sqlmodel  # noqa: F401 — used when autogenerate emits SQLModel column types

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3441b9fb9f25"
down_revision: str | Sequence[str] | None = "e30f18904b8f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subjects", sa.Column("org_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.create_index(op.f("ix_subjects_org_id"), "subjects", ["org_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_subjects_org_id"), table_name="subjects")
    op.drop_column("subjects", "org_id")
    # ### end Alembic commands ###
