"""swap documents.raw_content for r2_object_key

Revision ID: 4220579b8fb6
Revises: 7877073ae76d
Create Date: 2026-07-16 23:50:34.548126

"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401 — used when autogenerate emits pgvector column types
import sqlalchemy as sa
import sqlmodel  # noqa: F401 — used when autogenerate emits SQLModel column types
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4220579b8fb6"
down_revision: str | Sequence[str] | None = "7877073ae76d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents",
        sa.Column("r2_object_key", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.drop_column("documents", "raw_content")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents",
        sa.Column("raw_content", postgresql.BYTEA(), autoincrement=False, nullable=True),
    )
    op.drop_column("documents", "r2_object_key")
    # ### end Alembic commands ###
