"""add user_plans and generation_usage tables

Revision ID: 48c8dee79a2c
Revises: b27704cd2174
Create Date: 2026-07-17 17:55:26.704918

"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401 — used when autogenerate emits pgvector column types
import sqlalchemy as sa
import sqlmodel  # noqa: F401 — used when autogenerate emits SQLModel column types

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "48c8dee79a2c"
down_revision: str | Sequence[str] | None = "b27704cd2174"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "generation_usage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("kind", sa.Enum("quiz", "flashcard", name="generationkind"), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "day", "kind", name="uq_generation_usage_slot"),
    )
    op.create_index(op.f("ix_generation_usage_day"), "generation_usage", ["day"], unique=False)
    op.create_index(
        op.f("ix_generation_usage_owner_id"), "generation_usage", ["owner_id"], unique=False
    )
    op.create_table(
        "user_plans",
        sa.Column("owner_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("plan", sa.Enum("free", "pro", "business", name="plan"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("owner_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_plans")
    op.drop_index(op.f("ix_generation_usage_owner_id"), table_name="generation_usage")
    op.drop_index(op.f("ix_generation_usage_day"), table_name="generation_usage")
    op.drop_table("generation_usage")
    # ### end Alembic commands ###

    # Autogenerate doesn't emit these: on Postgres, `create_table` with a sa.Enum column
    # implicitly CREATEs the enum *type*, but `drop_table` does NOT drop it. Without
    # this, a downgrade leaves the types behind and the next upgrade fails with
    # "type ... already exists". (The pre-existing `documentstatus` enum migration has
    # this same gap; not repeating it here.) IF EXISTS keeps the downgrade re-runnable.
    op.execute("DROP TYPE IF EXISTS plan")
    op.execute("DROP TYPE IF EXISTS generationkind")
