"""add flashcard_review_states table

Revision ID: 5ccf38a52dfb
Revises: 3441b9fb9f25
Create Date: 2026-07-19 19:48:20.136779

"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401 — used when autogenerate emits pgvector column types
import sqlalchemy as sa
import sqlmodel  # noqa: F401 — used when autogenerate emits SQLModel column types

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5ccf38a52dfb"
down_revision: str | Sequence[str] | None = "3441b9fb9f25"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flashcard_review_states",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("flashcard_id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("repetitions", sa.Integer(), nullable=False),
        sa.Column("ease_factor", sa.Float(), nullable=False),
        sa.Column("interval_days", sa.Integer(), nullable=False),
        sa.Column("due_at", sa.DateTime(), nullable=False),
        sa.Column("last_reviewed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["flashcard_id"],
            ["flashcards.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "flashcard_id", "owner_id", name="uq_flashcard_review_state_card_owner"
        ),
    )
    op.create_index(
        op.f("ix_flashcard_review_states_due_at"),
        "flashcard_review_states",
        ["due_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flashcard_review_states_flashcard_id"),
        "flashcard_review_states",
        ["flashcard_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flashcard_review_states_owner_id"),
        "flashcard_review_states",
        ["owner_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_flashcard_review_states_owner_id"), table_name="flashcard_review_states")
    op.drop_index(
        op.f("ix_flashcard_review_states_flashcard_id"), table_name="flashcard_review_states"
    )
    op.drop_index(op.f("ix_flashcard_review_states_due_at"), table_name="flashcard_review_states")
    op.drop_table("flashcard_review_states")
    # ### end Alembic commands ###
