"""add assignment_submissions table

Revision ID: a1b2c3d4e5f6
Revises: faccee6a0508
Create Date: 2026-07-20 09:30:00.000000

Hand-written (not autogenerated): the live Neon DB is not yet up to date — the whole
Phase 5 migration chain (through `faccee6a0508` assignments and the flashcard-review-states
revision before it) is batched to the project-end live migration pass, so
`alembic revision --autogenerate` refuses to run ("target database is not up to date").
The DDL below mirrors `app.modules.assignments.models.AssignmentSubmission` exactly and
follows the same shape autogenerate emits for a plain-FK table with a UniqueConstraint
(see the flashcard-review-states migration `5ccf38a52dfb`). Applying this to Neon is a
pending live step recorded in docs/PROGRESS.md — do NOT run `alembic upgrade` against Neon
from here.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401 — used when autogenerate emits SQLModel column types

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1b2c3d4e5f6"
down_revision: str | Sequence[str] | None = "faccee6a0508"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "assignment_submissions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("assignment_id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("note", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assignment_id"],
            ["assignments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "assignment_id", "owner_id", name="uq_assignment_submission_assignment_owner"
        ),
    )
    op.create_index(
        op.f("ix_assignment_submissions_assignment_id"),
        "assignment_submissions",
        ["assignment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assignment_submissions_owner_id"),
        "assignment_submissions",
        ["owner_id"],
        unique=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f("ix_assignment_submissions_owner_id"), table_name="assignment_submissions")
    op.drop_index(
        op.f("ix_assignment_submissions_assignment_id"), table_name="assignment_submissions"
    )
    op.drop_table("assignment_submissions")
