"""add flashcards table

Revision ID: b27704cd2174
Revises: 066f42dbed80
Create Date: 2026-07-17 11:54:20.225727

"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401 — used when autogenerate emits pgvector column types
import sqlalchemy as sa
import sqlmodel  # noqa: F401 — used when autogenerate emits SQLModel column types

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b27704cd2174"
down_revision: str | Sequence[str] | None = "066f42dbed80"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flashcards",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("front", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("back", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("repetitions", sa.Integer(), nullable=False),
        sa.Column("ease_factor", sa.Float(), nullable=False),
        sa.Column("interval_days", sa.Integer(), nullable=False),
        sa.Column("due_at", sa.DateTime(), nullable=False),
        sa.Column("last_reviewed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_flashcards_due_at"), "flashcards", ["due_at"], unique=False)
    op.create_index(op.f("ix_flashcards_owner_id"), "flashcards", ["owner_id"], unique=False)
    op.create_index(op.f("ix_flashcards_subject_id"), "flashcards", ["subject_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_flashcards_subject_id"), table_name="flashcards")
    op.drop_index(op.f("ix_flashcards_owner_id"), table_name="flashcards")
    op.drop_index(op.f("ix_flashcards_due_at"), table_name="flashcards")
    op.drop_table("flashcards")
    # ### end Alembic commands ###
