"""add quiz_attempts table

Revision ID: b2c3d4e5f6a7
Revises: a1b2c3d4e5f6
Create Date: 2026-07-20 11:00:00.000000

Hand-written (not autogenerated) to match the Phase 5 migration convention and stay
deterministic: the DDL below mirrors `app.modules.quiz.models.QuizAttempt` exactly and
follows the shape autogenerate emits for a plain-FK table with a UniqueConstraint (see the
assignment_submissions migration `a1b2c3d4e5f6`). Unlike the earlier Phase 5 revisions,
this one IS applied to Neon in the same increment (Neon was brought to head at
`a1b2c3d4e5f6`), because the live app needs the `quiz_attempts` table immediately — a
missing table would be a live 500 on the first quiz attempt.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401 — used when autogenerate emits SQLModel column types

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b2c3d4e5f6a7"
down_revision: str | Sequence[str] | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "quiz_attempts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("quiz_id", sa.Uuid(), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("correct", sa.Integer(), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["quiz_id"],
            ["quizzes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("quiz_id", "owner_id", name="uq_quiz_attempt_quiz_owner"),
    )
    op.create_index(op.f("ix_quiz_attempts_quiz_id"), "quiz_attempts", ["quiz_id"], unique=False)
    op.create_index(
        op.f("ix_quiz_attempts_subject_id"), "quiz_attempts", ["subject_id"], unique=False
    )
    op.create_index(op.f("ix_quiz_attempts_owner_id"), "quiz_attempts", ["owner_id"], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f("ix_quiz_attempts_owner_id"), table_name="quiz_attempts")
    op.drop_index(op.f("ix_quiz_attempts_subject_id"), table_name="quiz_attempts")
    op.drop_index(op.f("ix_quiz_attempts_quiz_id"), table_name="quiz_attempts")
    op.drop_table("quiz_attempts")
