"""add embedding column to document_chunks

Revision ID: b31b86c196ef
Revises: 19324f4f8f37
Create Date: 2026-07-15 06:39:48.409163

"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401 — used when autogenerate emits pgvector column types
import sqlalchemy as sa
import sqlmodel  # noqa: F401 — used when autogenerate emits SQLModel column types

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b31b86c196ef"
down_revision: str | Sequence[str] | None = "19324f4f8f37"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_chunks",
        sa.Column(
            "embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=1024).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document_chunks", "embedding")
    # ### end Alembic commands ###
