"""add subject_id to document_chunks

Revision ID: ba1acb6a4b7c
Revises: b31b86c196ef
Create Date: 2026-07-15 07:03:58.341348

"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401 — used when autogenerate emits pgvector column types
import sqlalchemy as sa
import sqlmodel  # noqa: F401 — used when autogenerate emits SQLModel column types

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba1acb6a4b7c"
down_revision: str | Sequence[str] | None = "b31b86c196ef"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("document_chunks", sa.Column("subject_id", sa.Uuid(), nullable=False))
    op.create_index(
        op.f("ix_document_chunks_subject_id"), "document_chunks", ["subject_id"], unique=False
    )
    op.create_foreign_key(None, "document_chunks", "subjects", ["subject_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "document_chunks", type_="foreignkey")
    op.drop_index(op.f("ix_document_chunks_subject_id"), table_name="document_chunks")
    op.drop_column("document_chunks", "subject_id")
    # ### end Alembic commands ###
