"""add referral tables

Revision ID: e30f18904b8f
Revises: 4885e5ab676c
Create Date: 2026-07-19 11:42:30.754690

"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401 — used when autogenerate emits pgvector column types
import sqlalchemy as sa
import sqlmodel  # noqa: F401 — used when autogenerate emits SQLModel column types

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e30f18904b8f"
down_revision: str | Sequence[str] | None = "4885e5ab676c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "referral_attributions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("referrer_owner_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("referred_owner_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_referral_attributions_referred_owner_id"),
        "referral_attributions",
        ["referred_owner_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_referral_attributions_referrer_owner_id"),
        "referral_attributions",
        ["referrer_owner_id"],
        unique=False,
    )
    op.create_table(
        "referral_codes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_referral_codes_code"), "referral_codes", ["code"], unique=True)
    op.create_index(op.f("ix_referral_codes_owner_id"), "referral_codes", ["owner_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_referral_codes_owner_id"), table_name="referral_codes")
    op.drop_index(op.f("ix_referral_codes_code"), table_name="referral_codes")
    op.drop_table("referral_codes")
    op.drop_index(
        op.f("ix_referral_attributions_referrer_owner_id"), table_name="referral_attributions"
    )
    op.drop_index(
        op.f("ix_referral_attributions_referred_owner_id"), table_name="referral_attributions"
    )
    op.drop_table("referral_attributions")
    # ### end Alembic commands ###
