"""add assignments table

Revision ID: faccee6a0508
Revises: 5ccf38a52dfb
Create Date: 2026-07-20 00:12:55.434302

Hand-written (not autogenerated): the live Neon DB is not yet up to date — the prior
`5ccf38a52dfb` flashcard-review-states revision is itself batched to the project-end live
migration pass, so `alembic revision --autogenerate` refuses to run ("target database is
not up to date"). The DDL below mirrors `app.modules.assignments.models.Assignment`
exactly and follows the same shape autogenerate emits for a plain-FK table (see the
quizzes migration `5ffe4bd447ff`). Applying this to Neon is a pending live step recorded
in docs/PROGRESS.md — do NOT run `alembic upgrade` against Neon from here.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401 — used when autogenerate emits SQLModel column types

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "faccee6a0508"
down_revision: str | Sequence[str] | None = "5ccf38a52dfb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "assignments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("org_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("owner_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("quiz_id", sa.Uuid(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("due_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["quiz_id"],
            ["quizzes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_assignments_org_id"), "assignments", ["org_id"], unique=False)
    op.create_index(op.f("ix_assignments_owner_id"), "assignments", ["owner_id"], unique=False)
    op.create_index(op.f("ix_assignments_subject_id"), "assignments", ["subject_id"], unique=False)
    op.create_index(op.f("ix_assignments_quiz_id"), "assignments", ["quiz_id"], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f("ix_assignments_quiz_id"), table_name="assignments")
    op.drop_index(op.f("ix_assignments_subject_id"), table_name="assignments")
    op.drop_index(op.f("ix_assignments_owner_id"), table_name="assignments")
    op.drop_index(op.f("ix_assignments_org_id"), table_name="assignments")
    op.drop_table("assignments")
